version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

volumes:
  mongo_data: